# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Yao Zhang 张瑶
subtitle: 'Data Scientist & Ph.D. in Biomedical Engineering (BME)'
# description is mianly for SEO
description: "Welcome to my personal website, where you can learn about my PhD research projects in Biomedical Engineering (BME), 
Data Science (DS) & Artifical Intelligence (AI) related projects during internships and future work, and more."
keywords: PhD, BME, DS, AI, Healthcare, Photography
author: Yao Zhang
language: en
timezone: 'America/Chicago'

menu:
  About Yao: /about #you need to create "about" page first: PhD in BME at UT Austin, interested in DS and AI
  Projects: / # include publications and conferences; internship
  Publications: https://scholar.google.com/citations?hl=en&user=Sz_pAZEAAAAJ # https://scholar.google.com/citations?user=Sz_pAZEAAAAJ&hl=en #
  # Blog: /blog # write about your work experience, progress in photography, badminton, working out, cook, and growth
  # LinkedIn: https://www.linkedin.com/in/yao-zhang-bme/
  # Github: https://github.com/zhangyao1994
  # Twitter: https://twitter.com/zhangyao130
  # Facebook: https://www.facebook.com/YaoZhangLight
  # Instagram: https://www.instagram.com/yao.zhang_light/
  Email: mailto:zhangyao1994@gmail.com

  # if u want add more profile media social (icon same as Fontawesome 5)
#  just add name ex : Instagram: https://www.instagram.com/you/
# This does not work for edinburgh but worked for art_photo theme
# social:
#   LinkedIn: https://www.linkedin.com/in/yao-zhang-bme/
#   Github: https://github.com/zhangyao1994
#   Twitter: https://twitter.com/zhangyao130
#   Facebook: https://www.facebook.com/YaoZhangLight
#   Instagram: https://www.instagram.com/yao.zhang_light/
#   email: mailto:zhangyao1994@gmail.com

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://zhangyao1994.github.io/
root: /zhangyao1994.github.io/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: art_photo
# theme: landscape
theme: edinburgh

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://zhangyao1994.github.io/zhangyao1994.github.io/ #https://bitbucket.org/JohnSmith/johnsmith.bitbucket.io
